// 2. YEAR EXAM
// DMJX, INTERACTIVE DESIGN, JUNE 2022
// CODED BY EIGIL NIKOLAJSEN

let kdk = {
    game: {
        categories: {
            biller: {
                categoryName: "Biller",
                levels: {
                    1: {
                        level: 1,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 3,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "SYV-PLETTET marie-høne ",
                        hint1: "SYV-PLETTET Marie-Høne ",
                        hint2: "SYV-PLETTET Marie-HØNE ",
                        wincontent: {
                            beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.",
                            img2: "Mariehøne på blad",
                            forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.",
                            biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.",
                            img3: "Mariehøne i haven",
                            levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.",
                            udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.",
                        },
                    },
                    2: {
                        level: 2,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 3,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    3: {
                        level: 3,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 2,
                        hintsgiven: 1,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    4: {
                        level: 4,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 3,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    5: {
                        level: 5,
                        difficulty: "med",
                        unlocked: true,
                        playable: true,
                        completed: 1,
                        hintsgiven: 2,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    6: {
                        level: 6,
                        difficulty: "med",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    7: {
                        level: 7,
                        difficulty: "med",
                        unlocked: false,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    8: {
                        level: 8,
                        difficulty: "med",
                        unlocked: false,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    9: {
                        level: 9,
                        difficulty: "hard",
                        unlocked: false,
                        playable: false,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    10: {
                        level: 10,
                        difficulty: "hard",
                        unlocked: false,
                        playable: false,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    11: {
                        level: 11,
                        difficulty: "hard",
                        unlocked: false,
                        playable: false,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    12: {
                        level: 12,
                        difficulty: "hard",
                        unlocked: false,
                        playable: false,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                },
            },
            sommerfugle: {
                categoryName: "Sommerfugle",
                levels: {
                    1: {
                        level: 1,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 3,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "SYV-PLETTET marie-høne ",
                        hint1: "SYV-PLETTET Marie-Høne ",
                        hint2: "SYV-PLETTET Marie-HØNE ",
                        wincontent: {
                            beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.",
                            img2: "Mariehøne på blad",
                            forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.",
                            biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.",
                            img3: "Mariehøne i haven",
                            levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.",
                            udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.",
                        },
                    },
                    2: {
                        level: 2,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 3,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    3: {
                        level: 3,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 2,
                        hintsgiven: 1,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    4: {
                        level: 4,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 3,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    5: {
                        level: 5,
                        difficulty: "med",
                        unlocked: true,
                        playable: true,
                        completed: 1,
                        hintsgiven: 2,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    6: {
                        level: 6,
                        difficulty: "med",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    7: {
                        level: 7,
                        difficulty: "med",
                        unlocked: false,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    8: {
                        level: 8,
                        difficulty: "med",
                        unlocked: false,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    9: {
                        level: 9,
                        difficulty: "hard",
                        unlocked: false,
                        playable: false,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    10: {
                        level: 10,
                        difficulty: "hard",
                        unlocked: false,
                        playable: false,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    11: {
                        level: 11,
                        difficulty: "hard",
                        unlocked: false,
                        playable: false,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    12: {
                        level: 12,
                        difficulty: "hard",
                        unlocked: false,
                        playable: false,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    13: {
                        level: 9,
                        difficulty: "extreme",
                        unlocked: false,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    14: {
                        level: 10,
                        difficulty: "extreme",
                        unlocked: false,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    15: {
                        level: 11,
                        difficulty: "extreme",
                        unlocked: false,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                    16: {
                        level: 12,
                        difficulty: "extreme",
                        unlocked: false,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Syvplettet mariehøne",
                        hint0: "blåhat-jordbi ",
                        hint1: "BLÅhat-jordbi ",
                        hint2: "BLÅHAT-jordbi ",
                        wincontent: {
                            beskrivelse: "lorem_ipsum",
                            img1: "img_alt",
                            forvekslingsmuligheder: "lorem_ipsum",
                            biologi: "lorem_ipsum",
                            img2: "img_alt",
                            levested: "lorem_ipsum",
                            udbredelse: "lorem_ipsum",
                        },
                    },
                },
            },
            taeger: {
                categoryName: "Tæger",
            },
            bierogvepse: {
                categoryName: "Bier & vepse",
            },
            natsvaermere: {
                categoryName: "Natsværmere",
            },
            moel: {
                categoryName: "Møl",
            },
            guldsmede: {
                categoryName: "Guldsmede",
            },
            myreroggraeshopper: {
                categoryName: "Myrer & græshopper",
            },
            andreinsekter: {
                categoryName: "Andre insekter",
            },
        },
    },
}