// 2. YEAR EXAM
// DMJX, INTERACTIVE DESIGN, JUNE 2022
// CODED BY EIGIL NIKOLAJSEN

let kdk = {
    game: {
        categories: {
            biller: {
                categoryName: "Biller",
                levels: {
                    1: {
                        level: 1,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 3,
                        hintsgiven: 0,
                        insect: "7-plettet mariehøne",
                        hint0: "7-PLETTET marie-høne ",
                        hint1: "7-PLETTET Marie-Høne ",
                        hint2: "7-PLETTET Marie-HØNE ",
                        wincontent: {
                            beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.",
                            img2: "Mariehøne på blad",
                            forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.",
                            biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.",
                            img3: "Mariehøne i haven",
                            levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.",
                            udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.",
                        },
                    },
                    2: {
                        level: 2,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "Bladlus",
                        hint0: "bladlus ",
                        hint1: "Bladlus ",
                        hint2: "BLADlus ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    3: {
                        level: 3,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    4: {
                        level: 4,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    5: {
                        level: 5,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    6: {
                        level: 6,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    7: {
                        level: 7,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    8: {
                        level: 8,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    9: {
                        level: 9,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    10: {
                        level: 10,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    11: {
                        level: 11,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    12: {
                        level: 12,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    13: {
                        level: 13,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    14: {
                        level: 14,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    15: {
                        level: 15,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                    16: {
                        level: 16,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                },
            },
            sommerfugle: {
                categoryName: "Sommerfugle",
                levels: {
                    0: {
                        level: 0,
                        difficulty: "easy",
                        unlocked: true,
                        playable: true,
                        completed: 0,
                        hintsgiven: 0,
                        insect: "template_name",
                        hint0: "template_hint0 ",
                        hint1: "template_hint0 ",
                        hint2: "template_hint0 ",
                        wincontent: { beskrivelse: "Et af de mest velkendte insekter. En oval, stærkt hvælvet bille med røde dækvinger og syv sorte pletter. Hovedet og forkroppen er sort med hvide pletter. Den røde farve fungerer som advarselsfarve, der fortæller eventuelle fjender, at de bør holde sig væk pga. mariehønens dårlige lugt og smag. Længde 7-10 mm.", img2: "Insekt på blad", forvekslingsmuligheder: "Ligner overfladisk flere andre arter af mariehøns, men kan adskilles fra disse på antallet af sorte pletter og de hvide tegninger på hoved og forkrop.", biologi: "Lever overvejende af bladlus og i mindre grad af andre insekter samt pollen og svampesporer. Træffes fra det tidlige forår til sent efterår - af og til også på lune vinterdage. Overvintrer som voksen.", img3: "Blomst med insekt", levested: "Forekommer stort set overalt, hvor der er gode bestande af byttedyr, primært bladlus, i græsland, agerland, haver og parker samt på enge.", udbredelse: "Udbredt og almindelig over hele landet. I år med mange bladlus kan den optræde i enorme mængder, hvilket bl.a. kan ses langs kysterne, hvor den kan skylle op i bunkevis.", },
                    },
                },
            },
            taeger: {
                categoryName: "Tæger & cikader",
                levels: {

                },
            },
            bieroghvepse: {
                categoryName: "Bier & hvepse",
                levels: {

                },
            },
            natsvaermere: {
                categoryName: "Natsværmere",
                levels: {

                },
            },
            moel: {
                categoryName: "Møl",
                levels: {

                },
            },
            guldsmede: {
                categoryName: "Guldsmede",
                levels: {

                },
            },
            myreroggraeshopper: {
                categoryName: "Myrer & græshopper",
                levels: {

                },
            },
            andreinsekter: {
                categoryName: "Andre insekter",
                levels: {

                },
            },
        },
    },
}